log_level: INFO

defaults:
  - algos/ddpg

warmup_steps: 1000 # in step units
total_training_steps: 50000 # in step units
seed: 0
eval_interval: 1000 # in step units
eval_n_episodes: 100 
env_name: null
use_wandb: false

